### ISSUE TITLE
Omeka-S v2 compatibility

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-Mirador#1]
I see that Omeka v2.0.0 was released on August 8, and this module was last updated on Apr 23.

https://github.com/omeka/omeka-s/releases/tag/v2.0.0

Do you have any sense of when this module might be updated? I'm not clear on how significant the module changes required for compatibility are.

**Comment by hxsllc** [comment]
I got a response from jflatnes. Do you think this is the case for Mirador? Just edit the omeka_version_constraint variable?

> Omeka S 2.0.0 release upcoming: required change for modules
> https://forum.omeka.org/t/omeka-s-2-0-0-release-upcoming-required-change-for-modules/9098 
> 
> The easy case is modules that don’t add stuff to the API (no src/Api folder) and don’t hook into the API (no “api” events in Module.php): they generally don’t need any changes and can just have the omeka_version_constraint in module.ini edited to tack on || ^2.0.0
> 
> Even in the case where changes are needed, it’s almost always the case that the change needed is, as you say, “minimal”: the simple 1-to-1 replacement described in the post I linked.

**Comment by triplingual** [comment]
Made a config file change and created [a pull request](https://github.com/Daniel-KM/Omeka-S-module-Mirador/pull/2) for this.

**Comment by Daniel-KM** [comment]
This is pushed.
