### ISSUE TITLE
Initial zoom of thumbnail item with Mirador  v3

### ISSUE THREAD

**Issue by alfredobp** [Daniel-KM/Omeka-S-module-Mirador#13]
I have installed the viewpoint plugin, everything works fine, but when it is opened for the first time the image looks very small, when it is zoomed it appears correctly. Is there a way to modify the initial zoom?
Thanks

![imagen](https://user-images.githubusercontent.com/55509379/122170148-86efdd80-ce7e-11eb-8147-791200680265.png)

With i do zoom, appears well:

![imagen](https://user-images.githubusercontent.com/55509379/122170346-c4546b00-ce7e-11eb-8473-ba37394e75fd.png)

thanks

**Comment by Daniel-KM** [comment]
I don't check a lot all the plugins. It is provided by third parties, and I just copy them in the module. Nevertheless, in you case, it may be a css issue.
