### ISSUE TITLE
Problem with version 3.3.7.10

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-Mirador#14]
Mirador viewer is not visible and I get this in the console of the browser:

**_Uncaught TypeError: window.miradorPlugins is undefined
    <anonymous> http://.../modules/Mirador/asset/js/mirador.js?v=3.3.7.10:3
    jQuery 13
        e
        t
        setTimeout handler*l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>_**

**Comment by Falteri** [comment]
To solve the problem at least one plugin must be selected in config.

**Comment by Daniel-KM** [comment]
Thanks, it is fixed in 3.3.7.11.
