### ISSUE TITLE
Mirador plugin and IIIfServer

### ISSUE THREAD

**Issue by giulian** [Daniel-KM/Omeka-S-module-Mirador#19]
Hello,
we are working in a project where the integration of Omeka-s with the iiif world is a key point.
We are stucked on what seems to be a stupid point but we did not found any way to resolve.
We have an external IIIF server and a public manifest server. The first attempt was to install the Mirador plugin alone , but in all the attempts we made playing with the differents Item choice (DC "has format" has been populated and/or the straigtht iiif image in the media) we were not able to display any image.
A that point we installed even the IIIF Server. With that configuration we were able to open the client but we are non table to supprees the windows that Mirador open at startup (collection list). We passed in the site settings all the possibile parameter as  explained in settings.js but none of those has been able to avoid the opening of the windows.
Any idea?
Is the IIIF Server mandatory to have a working Omeka-S-module-Mirador ?
Thanks in advance
giuliano

**Comment by Daniel-KM** [comment]
Sorry, i miss the message.
To remove Mirador from the site, use module [BlocksDisposition](https://github.com/Daniel-KM/Omeka-S-module-BlocksDisposition) and fixed for Omeka S v4.

**Comment by giulian** [comment]
Hi Daniel,
Many thanks.
Giuliano
