### ISSUE TITLE
In Site > "name" > Settings. Missing configurations after upgrade from 3.1.2 to 3.1.3

### ISSUE THREAD

**Issue by tomvitale** [Daniel-KM/Omeka-S-module-Mirador#4]
Hi Daniel,

thank you for this great module.
After updating in the settings section of the site there are no "Append..." configurations as you can see in the screenshots.

Mirador v3.1.2
![Mirador_312](https://user-images.githubusercontent.com/25363918/71174935-9761d080-2266-11ea-892d-ff1c5e6c4f03.png)

Mirador v3.1.3
![mirador_313](https://user-images.githubusercontent.com/25363918/71174949-9df04800-2266-11ea-8023-8e8b2425abef.png)

**Comment by Daniel-KM** [comment]
Yes, they were removed, like in some other modules. In fact, all these settings are now managed by a single setting via the module [BlocksDisposition](https://github.com/Daniel-KM/Omeka-S-module-BlocksDisposition), so it's easier to manage for the admin and easier to maintain for me.

**Comment by tomvitale** [comment]
Thanks, work great.
I suggest to describe this plugin in the README.md file that I found also
very useful.
happy holidays

Tommaso Vitale


Il giorno ven 20 dic 2019 alle ore 06:57 Daniel Berthereau <
notifications@github.com> ha scritto:
