### ISSUE TITLE
Viewer not available at /item/{item id}/mirador

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-Mirador#7]
> The viewer is always available at http://www.example.com/item-set/{item-set id}/mirador and http://www.example.com/item/{item id}/mirador

Still not working for me after the last fix.

New install of Omeka-S v2.0.2:
http://vfl-test.reclaim.hosting/miradortest

1 item created
http://vfl-test.reclaim.hosting/miradortest/s/site1/item/1

3 images loaded

Modules installed:
Blocks Disposition version 3.2.0.1
Generic module version 3.0.12
Mirador Viewer version 3.1.6

Theme:
Center Row v1.4.2

I've created a user account for email address daniel@berthereau.net, will email you password. Not sure if needed, just created if helpful.

**Comment by hxsllc** [comment]
![Screen Shot 2020-02-04 at 12 07 12 PM](https://user-images.githubusercontent.com/29841283/73768416-f01df780-4746-11ea-935b-250908ca28a4.png)
![Screen Shot 2020-02-04 at 12 07 19 PM](https://user-images.githubusercontent.com/29841283/73768420-f1e7bb00-4746-11ea-930b-a2bbc5a78adb.png)

**Comment by Daniel-KM** [comment]
It is fixed in the version for Omeka 3.
